#ifndef PAGE_H
#define PAGE_H

#include <QList>
#include <QRectF>
#include "core/Global.h"

namespace QtWordEditor {

class Block;

/**
 * @brief The Page class represents a physical page generated by the layout engine.
 *
 * It contains references to blocks that appear on this page (non-owning).
 */
class Page
{
public:
    Page(int pageNumber, const QRectF &pageRect, const QRectF &contentRect);
    ~Page();

    int pageNumber() const;
    void setPageNumber(int number);
    QRectF pageRect() const;
    QRectF contentRect() const;

    // Block management
    int blockCount() const;
    Block *block(int index) const;
    void addBlock(Block *block);
    void clearBlocks();
    bool isEmpty() const;

private:
    int m_pageNumber;
    QRectF m_pageRect;
    QRectF m_contentRect;
    QList<Block*> m_blocks; // non-owning references
};

} // namespace QtWordEditor

#endif // PAGE_H