#ifndef SECTION_H
#define SECTION_H

#include <QObject>
#include <QList>
#include <QString>
#include "core/Global.h"

namespace QtWordEditor {

class Block;
class Page;

/**
 * @brief The Section class represents a logical section (e.g., a chapter) within a document.
 *
 * It contains a list of blocks and pages generated by the layout engine.
 */
class Section : public QObject
{
    Q_OBJECT
public:
    explicit Section(QObject *parent = nullptr);
    ~Section() override;

    int sectionNumber() const;
    void setSectionNumber(int number);

    QString header() const;
    void setHeader(const QString &header);

    QString footer() const;
    void setFooter(const QString &footer);

    // Blocks
    int blockCount() const;
    Block *block(int index) const;
    void addBlock(Block *block);
    void insertBlock(int index, Block *block);
    void removeBlock(int index);

    // Pages (runtime)
    int pageCount() const;
    Page *page(int index) const;
    void addPage(Page *page);
    void clearPages();

signals:
    void blockAdded(int index);
    void blockRemoved(int index);
    void pagesChanged();

private:
    int m_sectionNumber = 0;
    QString m_header;
    QString m_footer;
    QList<Block*> m_blocks;
    QList<Page*> m_pages; // owned by this section
};

} // namespace QtWordEditor

#endif // SECTION_H